### ISSUE TITLE
Missing recursions

### ISSUE THREAD

**Issue by TFarla** [dirkvanvugt01/recursion_fun#3]
[Can not find recursions](https://github.com/dirkvanvugt01/recursion_fun/issues/3)

**Comment by TFarla** [comment]
![z7ddmdij7q-am5mbmcesp4wtqpvi-dvvftqxu380ves](https://user-images.githubusercontent.com/4613944/41376704-45d24148-6f5a-11e8-9898-520a4d3c0663.png)

**Comment by TFarla** [comment]
![ju110ff57nxlyfdvpfzh1eupte3wy2jo9aepngkkit0](https://user-images.githubusercontent.com/4613944/41511649-7d86dca6-727b-11e8-8eb6-e024434cfa46.jpg)

**Comment by dirkvanvugt01** [comment]
Thanks for improving repo 👍

**Comment by TFarla** [comment]
It actually has some recursion now
